use crate::IpcError;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Message sent by the editor to the runtime.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMessage {
    /// Initial handshake with protocol version and launch token.
    Hello {
        /// Protocol version supported by the editor.
        protocol_version: u32,
        /// Token generated by the editor when launching the runtime.
        token: u64,
    },
    /// Request that the runtime perform a command.
    Command {
        /// Client-generated request id used to match the response.
        id: u64,
        /// Command method name.
        method: String,
        /// Command-specific JSON parameters.
        #[serde(default)]
        params: Value,
    },
}

/// Message sent by the runtime to the editor.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RuntimeMessage {
    /// Runtime-pushed event without a request id.
    Event {
        /// Event name.
        event: RuntimeEvent,
        /// Event-specific JSON payload.
        #[serde(default)]
        payload: Value,
    },
    /// Response to a prior client command.
    Response {
        /// Request id from the original command.
        id: u64,
        /// Whether the command succeeded.
        ok: bool,
        /// Optional successful result payload.
        #[serde(skip_serializing_if = "Option::is_none")]
        result: Option<Value>,
        /// Optional error for failed responses.
        #[serde(skip_serializing_if = "Option::is_none")]
        error: Option<IpcError>,
    },
}

/// Runtime event names pushed over IPC.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuntimeEvent {
    /// Runtime accepted the handshake and is ready for commands.
    RuntimeReady,
    /// Runtime log message.
    Log,
    /// Runtime scene hierarchy snapshot.
    SceneSnapshot,
    /// Runtime frame timing statistics.
    FrameStats,
}
